### ISSUE TITLE
安全模式连接Hbase时，提示AppConfigurationEntry named Client does not have keyTab value

### ISSUE THREAD

**Issue by zqr10159** [AlionSSS/EveHBase#1]
安全模式连接Hbase时，提示AppConfigurationEntry named Client does not have keyTab value，但实际上user.keytab文件之前一直可用，之前连es和kafka都没问题，麻烦看看

**Comment by zqr10159** [comment]
![image](https://github.com/AlionSSS/EveHBase/assets/30048352/27619583-d469-43a2-93bb-b8b70467148a)

**Comment by AlionSSS** [comment]
- 抱歉😂时间比较久了，我现在也没华为的集群可以测试，你可以试试这个方法：
  - 你配置keytab文件时，路径试试用`/`传，不要用`\\`
- 出错大致原因在 https://github.com/AlionSSS/EveHBase/blob/master/src/com/skey/evehbase/security/LoginUtil.java 中的`192:200`行处代码，你可以打断点试试，看看这里`equals`比较的两个值的区别。

**Comment by zqr10159** [comment]
收到，非常感谢，我明天试试看给您回复

**Comment by zqr10159** [comment]
可以了，感谢

**Comment by AlionSSS** [comment]
> 可以了，感谢

OK
